### ISSUE TITLE
Specifying equalities in SDP

### ISSUE THREAD

**Issue by sashasami03** [peterwittek/ncpol2sdpa#6] opened 2015-09-03 04:21 UTC
I was trying to see the maximum hardy violation in quantum case for a bipartite scenario.
According to Hardy if : 
P(00|00)  =  0     ........(a)
P(01|10)  =  0     ........(b)
P(10|01)  =  0     .........(c)

then q_{Hardy} = P (00|11) has to be zero  if P lies in local hidden variable polytope ( equation (1) - (2) of the paper : http://arxiv.org/abs/1402.1850 ). But for quantum case q_{Hardy} can be greater than zero, 
maximum being  ~ 0.09 ( to be exact  (5 \* sqrt(5) - 11)/2  , as suggested by Figure 1 of the same paper ).
I wanted to get q_ {Hardy} = P(00|11) = 0.09 by setting the equalities (a)-(c). I set the equalities by
passing the list equalities in SDP. But my maximum q_{Hardy} came out to be zero. To check when I printed the values of terms (a)-(c) all of them were not set to zero. Is this the correct way to set the equalities ? What I tried : https://gist.github.com/sashasami03/45075074b39f3d013261 .
I also tried giving the equalities as inequalities ( both ways ) but got the same result. I hope I am not making a silly mistake again, but independent of what value of q_{Hardy} I should get , the terms that I set to zero in equalities are not all being set to 0.

**Comment by peterwittek** [comment] 2015-09-03 04:46
This one is extremely confusing about the NPA hierarchy. The numerical values from the get_xmat_values are on the order of 10^12 to 10^-9 with the various solvers, so they are technically zeros. That is not the issue. The issue is _what kind_ of equality you have at hand. This is probably best spelt out in the handbook version of the NPA paper ([doi:10.1007/978-1-4614-0769-0_21](http://dx.doi.org/10.1007/978-1-4614-0769-0_21)). You either have an equality in the noncommutative variables or in their moments. In the latter case, they do not have to be relaxed with localizing matrices and they are added as ordinary linear constraints on the SDP. These kinds of constraints are supplied as bounds in Ncpol2sdpa and the equalities on the probabilities are also always of this kind (see the example on the Nieto-Silleras hierarchy). I commented on your gist with a version that gives the expected 0.09.

**Comment by sashasami03** [comment] 2015-09-10 14:32
Running the code with solver as sdpa gives the correct result but with solver = cvxopt it gives
division by zero error.

**Comment by peterwittek** [comment] 2015-09-11 00:24
Both SDPA and Mosek give the correct result, I tried it at level 2 and 3. This is why I recommend these two solvers. Unfortunately, Cvxopt still has many bugs. Since this is unrelated to Ncpol2sdpa, I close the issue.

**Closed as completed by peterwittek** 2015-09-11 00:24 UTC

**Comment by sashasami03** [comment] 2015-09-19 01:59
@peterwittek I am really sorry but I am still unclear about equalities/inequalities on the non-commutative variables ( the projector operators in my case ) and their moments. I tried the following two things : 
1. In bounds I set an invalid equality (  P([0,0], [0, 0]) = 2  ) , but yet the SDP runs and gives an output, I expected it to return an infeasible solution. The link to the gist :  https://gist.github.com/sashasami03/4c302d73d056d6562a2f .
2. I wanted to set some moments ( values corresponding to some variables ) equal to zero, which I did
   by using 'bounds'. But in addition to this I also wanted to set some inequalities on the moments so I   used 'inequalities' for that. If I specify only bounds and run the SDP the moments as expected are all set to zero, but if I add the inequalities also and run the SDP the moments which should be set to zero are no longer set to zero. Link to the gist : https://gist.github.com/sashasami03/776f595c39c471076196.

As both my examples are in relation to a 2 party scenario I ran SDP with level = 2. As far as my second 
example is concerned I am sure I am again confusing between moments and variables. But for my first 
example as I am running with level = 2 and it's a bipartite scenario all P(a,b|x,y) come along the diagonal in the moment matrix and thus are greater than 0, and if I am not wrong the relation among the non-commutative variables which is specified in the 'substitutions' takes care of the no-signalling conditions on the moments p(a,b|x,y) making P(a,b|x,y) a valid probability distribution. Thus I am not sure why SDP runs even if I set p(a,b|x,y) = 2 in the bounds.

I am really sorry for bothering you again and again,  I just wanted to know how relation between variables specified in 'substitutions'  makes their moment a valid probability distribution ( my example (1) ) and how are equalities/inequalities set for variables and their moments.

**Comment by peterwittek** [comment] 2015-09-19 06:44
For 1), it actually gives an unbounded result. Please print the status and the dual too:

``` python
print(abs(sdpRelaxation.primal), sdpRelaxation.dual, sdpRelaxation.status)
```

If you solve it with mosek, it reports `dual_infeas_cer`. So it clearly figures out that something is wrong with the SDP, and it depends on the solver what kind of error message you get in the status.

**Comment by peterwittek** [comment] 2015-09-19 07:03
As for 2), if you add inequalities this way, you declare the inequalities in the operators and not the moments. The difference is as follows: assume that we have an operator `X`. Its first moment is `<X>`.
- An example inequality constraint on this operator is that it is positive semidefinite: `X > 0`. To write in the code, you can say `inequalities=[ X>0]`, or, more concisely, `inequalities=[X]`. This will build a moment matrix for the constraint in the relaxation.
- On the other hand, if we want to say something about its moments, than we use bounds. If we want to say its first moment is positive (`<X> > 0`), we could write concisely `bounds=[X]`. If we want to say it is zero, we could write `bounds=[X, -X]`.

So in your code, instead of defining inequalities, you should extend your set of bounds. The numbers will still not be right, as the SDP is unfeasible.

**Comment by peterwittek** [comment] 2015-09-19 07:11
To study why it is infeasible, you can write out the relaxation in a human-readable form:

`write_to_human_readable(sdpRelaxation, "debug.csv")`

At the operator level, your constraints indeed look contradictory.
